# Generated by Django 6.0.6 on 2026-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_remove_filechange_additions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='classes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filechange',
            name='complexity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filechange',
            name='functions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filechange',
            name='loops_count',
            field=models.IntegerField(default=0),
        ),
    ]
